connection: &connection
  adapter: postgresql
  encoding: unicode
  host:     localhost
  pool: 5
  username: postgres
  password: password

development:
  <<: *connection
  database: movie_index

test: &test
  <<: *connection
  database: movie_index_test

production:
  <<: *connection
  database: movie_index_production
